//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationControlee
    {
        public int Id_app { get; set; }
        public bool Est_actif { get; set; }
        public int Tps_exe_restant { get; set; }
        public Nullable<System.DateTime> Tps_limite_atteinte { get; set; }
    
        public virtual ApplicationControlable ApplicationControlable { get; set; }
        public virtual TempsDefini TempsDefini { get; set; }
    }
}
