//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historique
    {
        public int Id_app { get; set; }
        public System.DateTime Date { get; set; }
        public int Temps_total { get; set; }
    
        public virtual ApplicationControlable ApplicationControlable { get; set; }
    }
}
