//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWindowsForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppSmartLockerEntities1 : DbContext
    {
        public AppSmartLockerEntities1()
            : base("name=AppSmartLockerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationControlable> ApplicationControlables { get; set; }
        public virtual DbSet<ApplicationControlee> ApplicationControlees { get; set; }
        public virtual DbSet<Historique> Historiques { get; set; }
        public virtual DbSet<TempsDefini> TempsDefinis { get; set; }
    }
}
