//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempsDefini
    {
        public int Id_app { get; set; }
        public Nullable<int> Duree_blocage { get; set; }
        public Nullable<int> Lundi { get; set; }
        public bool Lundi_actif { get; set; }
        public Nullable<int> Mardi { get; set; }
        public bool Mardi_actif { get; set; }
        public Nullable<int> Mercredi { get; set; }
        public bool Mercredi_actif { get; set; }
        public Nullable<int> Jeudi { get; set; }
        public bool Jeudi_actif { get; set; }
        public Nullable<int> Vendredi { get; set; }
        public bool Vendredi_actif { get; set; }
        public Nullable<int> Samedi { get; set; }
        public bool Samedi_actif { get; set; }
        public Nullable<int> Dimanche { get; set; }
        public bool Dimanche_actif { get; set; }
    
        public virtual ApplicationControlee ApplicationControlee { get; set; }
    }
}
